export 'resources/resources.dart';
export 'widgets/widgets.dart';
export 'package:flutter/material.dart';
export '../router/router.dart';
export '../../gen/assets.gen.dart';
export 'dimens/dimens.dart';
export 'extensions/extensions.dart';
export 'resources/design/design.dart';
export 'generated/l10n.dart';